services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    ports:
      - 1998:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./aruna-server/tests/test_db/realm.json:/opt/keycloak/data/import/realm.json
    command: "start-dev --import-realm"
