on:
  - push
  - pull_request
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - uses: arduino/setup-protoc@v1
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: remove .cargo
        run: rm -rf ~/.cargo
      - name: Setup
        run: docker compose -f compose.yaml up -d
      - uses: dtolnay/rust-toolchain@stable
      - run: CARGO_NET_GIT_FETCH_WITH_CLI=true cargo test --all-features
